### ISSUE TITLE
Add link to GitHub repository automatically on each extension doc

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkiverse-docs#100]
👆

**Comment by holly-cummins** [comment]
There's already an indirect version of this capability. If you know to click the 'edit this page' link, you can get to the github repo – but that's obviously dependent on people knowing the trick. :) 

This also raises some interesting questions about how much overlap we want between the various sites, such as code.quarkus.io, docs.quarkiverse.io, and extensions.quarkus.io. For example, https://github.com/quarkusio/extensions/issues/251 covers putting part of the docs on the main panel on extensions.quarkus.io, so it's sort of the opposite of this issue; if we did both, the two sites would become very similar.

From an implementation point of view, the overlap is slightly irritating, because it means duplicated code. From a user perspective, however, I can't think of any downside. Well, no downside as long as the 'extra' content doesn't add so much clutter that interferes with the core function of the site. For example, we'd want to carefully limit the amount of information on code.quarkus.io, because otherwise it becomes hard to use for app creation. The other thing we want to be cautious of is having so much overlap that users get confused about why we have several sites and what they should do on each one. 

However, I think we will see more convergence between the three/four sites as time goes on. 

(And the TLDR of that comment for this request is that I agree we should do it. :) )

**Comment by jmini** [comment]
I was about to open the same issue, because right now I am using the 'edit this page' link for that and then manually edit the location in the address bar or click on the project name to go back to the github home of the project.

Often I click on the 🏠 icon in the bar (because I am thinking let's go to the github home), and then I regret my click.

<img width="627" alt="Screenshot 2024-09-12 at 11 13 50" src="https://github.com/user-attachments/assets/331c1c3f-9142-4721-8a54-00b31d532950">

--> if there is an option in Antora to hide this button you should do it, since you already have the logo at the top left corner to go to the "Quarkiverse documentation" page.

---

For me a button (with the github logo or whatever) would be perfect:

<img width="1056" alt="Screenshot 2024-09-12 at 11 06 49" src="https://github.com/user-attachments/assets/6314de55-39ec-4cea-986a-7a751031257d">

---

And then, maybe it is out-of-scope for this issue, but I think you should make sure (or encourage the maintainer to configure it) that each quarkiverse project that has a guide also sets its guide as github project's website. This way you would have a standard link to the guide:

<img width="612" alt="Screenshot 2024-09-12 at 11 17 24" src="https://github.com/user-attachments/assets/4067a6fa-8a5e-44d8-a41f-74df58cbc4a8">

**Comment by holly-cummins** [comment]
> And then, maybe it is out-of-scope for this issue, but I think you should make sure (or encourage the maintainer to configure it) that each quarkiverse project that has a guide also sets its guide as github project's website. This way you would have a standard link to the guide:
> <img alt="Screenshot 2024-09-12 at 11 17 24" width="612" src="https://private-user-images.githubusercontent.com/1222165/366807569-4067a6fa-8a5e-44d8-a41f-74df58cbc4a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDEwMzcsIm5iZiI6MTcyNjE0MDczNywicGF0aCI6Ii8xMjIyMTY1LzM2NjgwNzU2OS00MDY3YTZmYS04YTVlLTQ0ZDgtYTQxZi03NGRmNThjYmM0YTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTEzMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NmZmZhNjFiM2NhNDFlY2U1YzUyNWIwODgwMmQyOGU0M2ExMmZiZTIzZGY2ZTIzOGFjOTA4ODk5MjMxODJmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZQKX6zgZY1f8phgBJkfmhywZQapGrGGMcUJuux_lqHw">

That would definitely be a different issue. @gastaldi, could the terraform scripts and the registry cooperate in some way to do that? I'm thinking get the extension list from the registry, for anything with an `scm-url` that points to the quarkiverse, update the repo description to include the guide link as the last line?

**Comment by holly-cummins** [comment]
Thanks, @gastaldi. Could we automate it? So it wasn't done manually? I guess that's probably more effort than it's worth.

**Comment by gastaldi** [comment]
Probably once (and if) we automate the creation of the Terraform scripts someday :)
