### ISSUE TITLE
Add a Favicon for the Quarkiverse doc

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkiverse-docs#113]
See https://docs.quarkiverse.io/quarkus-web-bundler/dev/

https://github.com/quarkiverse/quarkus-web-bundler/blob/main/docs/modules/ROOT/pages/includes/attributes.adoc#L5

**Comment by holly-cummins** [comment]
I think having an individual favicon per sub-site may be too much to do, both because it's a big lift, technically, and also because it's not something many sites do. Most sites have a favicon for the whole site, and it doesn't change when you navigate around the site. (@ia3andy, if you have counter-examples where the favicon does change within a site, hit me with them.) 

However, I agree that, at the very least, the overall docs site should have a favicon, so I'll do that now.

**Comment by ia3andy** [comment]
That's good for me :)

**Comment by holly-cummins** [comment]
(I can see that the `:favicon` attribute is a standard Asciidoctor thing, but intended for when a standalone html document will be generated: https://docs.asciidoctor.org/asciidoctor/latest/html-backend/favicon/ ... Antora, which is what we're using, don't have that level of support: https://gitlab.com/antora/antora/-/issues/334 ... which doesn't mean we shouldn't have a favicon, but I think it does mean we don't need to feel we have to do it per sub-site.)

**Comment by holly-cummins** [comment]
I've put the favicon into the antora template, so it should propagate through to the docs site by the end of the day. I've also done a favicon for http://quarkiverse.io, which was missing it. Thanks for noticing, @ia3andy!

**Comment by melloware** [comment]
Awesome change!  Gonna fix all my Extensions.

**Comment by holly-cummins** [comment]
> Awesome change! Gonna fix all my Extensions.

Before you get too excited, I've hardcoded it at the site level. I think doing it at the extension-level is a lot harder, so I wimped out (for now).

**Comment by melloware** [comment]
Ahh! OK totally understand.
