### ISSUE TITLE
Categories: Test and Testing

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkiverse-docs#114]
@holly-cummins I think we should fix the extensions there should only be 1 category either Test or Testing but not both.

![image](https://github.com/quarkiverse/quarkiverse-docs/assets/4399574/09a45c3f-54d6-4f4e-a6c7-bdb18f31c69d)

Let me know what you choose because my new Mail extension will use whichever category you pick.

**Comment by gastaldi** [comment]
+1 for "Testing"

**Comment by melloware** [comment]
+1 for Testing also.

**Comment by melloware** [comment]
also @holly-cummins @ia3andy I just submitted this for PlayWright but I don't see PlayWright showing up in the docs pages?

https://github.com/quarkiverse/quarkus-playwright/pull/12

**Comment by holly-cummins** [comment]
> also @holly-cummins @ia3andy I just submitted this for PlayWright but I don't see PlayWright showing up in the docs pages?
> 
> [quarkiverse/quarkus-playwright#12](https://github.com/quarkiverse/quarkus-playwright/pull/12)

The docs site is static, and rebuilt ... maybe twice a day? However, I can see the last change to https://github.com/quarkiverse/quarkiverse-docs/blob/main/antora-playbook.yml was three weeks ago (and playwright is in there), so ... um ... not obvious to me either.

**Comment by holly-cummins** [comment]
I've raised https://github.com/quarkiverse/quarkus-groovy/pull/60

**Comment by melloware** [comment]
The only thing I can tell and not sure if it matters is PlayWright uses `test` as a folder instead of `runtime` like most other projects where the `extension.yaml` is located?

**Comment by holly-cummins** [comment]
@melloware, for Playwright not being on the docs pages, do you mean it's not on https://quarkus.io/extensions/, or that it's not on https://docs.quarkiverse.io?

In fairness, it's not on either, so probably there's actually two problems, but the fixes are probably different. For the extensions site, the fix is to add it to https://github.com/quarkusio/quarkus-extension-catalog/tree/main/extensions. That step is referenced in https://hub.quarkiverse.io/checklist/, and the full instructions are here: https://github.com/quarkusio/quarkus-extension-catalog#extensions ... but it's pretty easy to miss.

**Comment by melloware** [comment]
OK I blame @ia3andy 😄 let me submit a PR to add it to the extensions site.
