### ISSUE TITLE
Categories: Alphabetical order

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkiverse-docs#122]
Shouldn't this list be in Alpha order?

![image](https://github.com/quarkiverse/quarkiverse-docs/assets/4399574/e304eb43-bc76-4ef8-82e0-5c65312e94df)

**Comment by gastaldi** [comment]
I must admit that some are not that comprehensible (eg. WTF is `Cdc`?)

**Comment by melloware** [comment]
HA i totally agree that is why i was looking at what Category to put something in I had no idea what some of these meant.

**Comment by melloware** [comment]
OK its for Change Data Capture technology but that really should just be "Data" category.

**Comment by holly-cummins** [comment]
They're sorted by popularity, so that the obscure ones are at the bottom. Within that, I think they're alphabetical. 

However, @gastaldi's point is also a good one. We're seeing a proliferation of categories, and it's supposed to be - unlike keywords - a relatively small set. Anything that's not a category in the list on http://code.quarkus.io won't be searchable by that category on code.quarkus. Fixing that will need a combination of hand-curation when we spot outliers, and also more help when people create extensions to show them the current list and invite them to select something from it unless they have a really good reason not to.

**Comment by holly-cummins** [comment]
This issue should be over on https://github.com/quarkusio/extensions, I think. I should put a link on the extensions site to make raising issues and changing source easier.

**Comment by melloware** [comment]
Ok I will close this one.
