### ISSUE TITLE
Link to the JavaDocs

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkiverse-docs#197]
It would be nice to have a link to the JavaDocs as part of the template. We could use https://javadoc.io, as in the example:

https://javadoc.io/doc/io.quarkiverse.githubapp/quarkus-github-app/latest/index.html

**Comment by gsmet** [comment]
The link they advertise is https://javadoc.io/doc/io.quarkiverse.githubapp/quarkus-github-app .

**Comment by gastaldi** [comment]
@holly-cummins what are your thoughts about it? Also I think I should move this to https://github.com/quarkiverse/antora-ui-quarkiverse

**Comment by holly-cummins** [comment]
We do derive a javadoc link on http://quarkus.io/extensions (done under https://github.com/quarkusio/extensions/issues/1016). I agree it would also be extremely logical to show a javadoc link on the quarkiverse docs pages. 

One hesitation is that only some extensions provide javadoc. See, for example, https://javadoc.io/doc/io.quarkiverse.amazonalexa/quarkus-amazon-alexa. For extensions that don't, there's still a https://javadoc.io/ link for the page, but it basically says "nothing to see here, move along" if you visit it. So for the extensions pages, in those cases, we don't show the link, because there's no benefit to anyone clicking on it. 

It would be good to do a similar screening on the antora side, but I don't know how to do it in the antora processing. There's a link visit, and also a persistent cache. To get that slightly more complex logic implemented, it might need to be a pre-processing step. Or, if this is shared information, we could do it somewhere on the registry ingestion/output, so that there's a single source of truth. 

https://github.com/quarkusio/extensions/blob/ac6f67c7a369efef94c8b70b587900421bf8906c/src/javadoc/javadoc-url.js#L31-L42 is the current url validation logic. 

Alternatively, we could say this in this context, where validation is complicated, the price of trying to do validation is higher than 'do not show disappointing javadoc links' is worth. The first two quarkiverse extensions I checked (going by 'recently released') don't publish javadoc – but then the next three I checked did have javadoc, so 🤷

**Comment by gastaldi** [comment]
Ah forgot that you have already done it on the http://quarkus.io/extensions page. I wonder if we should link from the docs.quarkiverse.io to this page (eg. a `Click here for more information about this extension` link)

**Comment by ppalaga** [comment]
I'd like to point out that we never cared much for JavaDoc in Camel Quarkus and Quarkus CXF. Even if we cared, I do not think there would be much to see for extension end users. Looking into JavaDoc might even by rather confusing for beginners. What is the purpose of adding those links to JavaDoc from your perspective, @gastaldi and @holly-cummins?

**Comment by gastaldi** [comment]
The link to the Javadocs is already present in the quarkus.io/extensions URL, I believe this can be closed.
